# BEGIN
spring:
  datasource:
    url: "jdbc:h2:file:./test"
    username: admin
    password: admin
    generate-unique-name: false

    h2:
      console:
        enabled: true
        settings.web-allow-others: true
# END
