---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  datasource:
    url: "jdbc:h2:mem:dev"
    username: sa
    password: 123
    generate-unique-name: false
  h2:
    console:
      enabled: true
      settings.web-allow-others: true